### PR TITLE
implement gradient masking with cropping - new PR

### PR DESCRIPTION
**Pull request by JonasHell**
I cleaned my git repo. Unfortunately, renaming of branches leads to the closing of connected PRs. So I opened a new one. To not loose the old discussion, I link the old PR [here](https://github.com/constantinpape/torch-em/pull/90).

### CODE REVIEW

**Comment by constantinpape** [comment]
Thanks @JonasHell. I will have a look soon.

**Review by constantinpape — COMMENTED** [review]
Thanks for working on this! The changes to `loss_wrapper.py` all look good to me.
It would be good to extend the test cases a bit to cover all the changes:
- In `test_masking`: test for both `crop` and `multiply` masking methods that the masked gradients are zero. (Can just put this in a loop where `ApplyAndRemoveMask` is called with the corresponding argument.) The test could also be renamed to `test_ApplyAndRemove...` to make the naming more consistent.
- Add a test for `MaskIgnoreLabel` along the lines of `test_masking`.

**Comment by JonasHell** [comment]
Done :)
Let me know if you want to have more tests.

**Review by constantinpape — APPROVED** [review]
The tests look good now. Thanks!

**Pull request merged**
