### PR TITLE
Add Raw Transform - nnUNet

### PR DESCRIPTION
**Pull request by anwai98**
Creating a base class and child class (for CT/PET-CT normalization scheme) for the raw transformation implementation.
(maybe it's better if I handle inputs as tensors in the raw transform (instead of arrays as of now), but not 100% sure)

### CODE REVIEW

**Comment by anwai98** [comment]
@constantinpape This looks good to go (as discussed)

**Review by constantinpape — APPROVED** [review]

**Review by constantinpape — COMMENTED** [review]
I realized there is a bit more subtlety to this.

**Comment by anwai98** [comment]
I updated the raw transform now. It expects channels (modalities) first, and does the transformation automatically for the entire multi-modal input(s) (considering the inputs are 2 * H * W * D - for our case). Is this desired?

**Comment by anwai98** [comment]
This is taken care of now (with the mentions). Thanks!

**Pull request merged**
